return {
    rust = {
        arguments = true,
        array_expression = true,
        attribute_item = true,
        block = true,
        declaration_list = true,
        field_declaration_list = true,
        macro_definition = true,
        match_block = true,
        meta_arguments = true,
        parameters = true,
        parenthesized_expression = true,
        tuple_pattern = true,
        tuple_struct_pattern = true,
        type_arguments = true,
        type_parameters = true,
        unit_type = true,
        use_list = true,
    },
    lua = {
        variable_declaration = true,
        local_variable_declaration = true,
        function_call = true,
        arguments = true,
        local_function = true,
        ["function"] = true,
        if_statement = true,
        for_statement = true,
        for_in_statement = true,
        repeat_statement = true,
        return_statement = true,
        while_statement = true,
        table = true,
        do_statement = true,
    },
    query = {
        named_node = true,
        grouping = true,
        list = true,
    },
}
