return {
    rust = {
        arguments = true,
        array_expression = true,
        attribute_item = true,
        block = true,
        declaration_list = true,
        field_declaration_list = true,
        index_expression = true,
        macro_invocation = true,
        macro_definition = true,
        match_block = true,
        meta_arguments = true,
        parameters = true,
        parenthesized_expression = true,
        struct_expression = true,
        tuple_expression = true,
        tuple_pattern = true,
        tuple_struct_pattern = true,
        tuple_type = true,
        type_arguments = true,
        type_parameters = true,
        unit_type = true,
        use_list = true,
    },
    query = {grouping = true, list = true, named_node = true},
    c = {
        array_declarator = true,
        call_expression = true,
        for_statement = true,
        function_definition = true,
        enumerator_list = true,
        field_declaration_list = true,
        initializer_list = true,
        parameter_list = true,
        parenthesized_expression = true,
        subscript_expression = true,
    },
    cpp = {
        array_declarator = true,
        call_expression = true,
        compound_statement = true,
        condition_clause = true,
        declaration_list = true,
        enumerator_list = true,
        field_declaration_list = true,
        initializer_list = true,
        parameter_list = true,
        parenthesized_expression = true,
        subscript_expression = true,
        template_parameter_list = true,
        template_type = true,
    },
    fennel = {
        assignments = true,
        do_statement = true,
        each = true,
        each_clause = true,
        function_call = true,
        function_definition = true,
        if_statement = true,
        let_definition = true,
        parameters = true,
        require = true,
        sequential_table = true,
        set = true,
        table = true,
        var_definition = true,
        when_statement = true,
    },
    jsx = {jsx_element = true, jsx_closing_element = true, jsx_expression = true},
    ecma = {
        class_body = true,
        statement_block = true,
        parenthesized_expression = true,
        formal_parameters = true,
        new_expression = true,
        call_expression = true,
        object = true,
        array = true,
    },
    elixir = {
        arguments = true,
        tuple = true,
        list = true,
        binary = true,
        block = true,
    }
}
